# Generated by Django 2.1.4 on 2019-01-25 11:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=300, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumeric or contain numbers', regex='^[a-zA-Z0-9.+-]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('location', models.CharField(choices=[('LHR', 'Lahore'), ('ISL', 'Islamabad'), ('KHI', 'Karachi'), ('PEW', 'Peshawar'), ('QTA', 'Quetta')], default='LHR', max_length=3)),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
