# Generated by Django 2.1.4 on 2019-01-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190125_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_number',
            new_name='update_count',
        ),
    ]
