# Generated by Django 2.1.5 on 2019-01-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dateconversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='update_count',
            new_name='user_number',
        ),
    ]
