# Generated by Django 2.1.5 on 2019-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190131_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateconversion',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In Progress'), ('converted', 'Converted')], default='inprogress', max_length=50),
        ),
    ]
